// Code generated by "stringer -type=GameLogLineType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GameLogLineTypeConnected-0]
	_ = x[GameLogLineTypeAddPlayer-1]
	_ = x[GameLogLineTypePlayerLeave-2]
	_ = x[GameLogLineTypeNetStat-3]
	_ = x[GameLogLineTypeGameFinished-4]
}

const _GameLogLineType_name = "GameLogLineTypeConnectedGameLogLineTypeAddPlayerGameLogLineTypePlayerLeaveGameLogLineTypeNetStatGameLogLineTypeGameFinished"

var _GameLogLineType_index = [...]uint8{0, 24, 48, 74, 96, 123}

func (i GameLogLineType) String() string {
	if i < 0 || i >= GameLogLineType(len(_GameLogLineType_index)-1) {
		return "GameLogLineType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameLogLineType_name[_GameLogLineType_index[i]:_GameLogLineType_index[i+1]]
}
