// Code generated by goyacc -o ./combat/gramma.go -l ./combat/gramma.y. DO NOT EDIT.
package combat

import __yyfmt__ "fmt"

type (
	Int     = int
	String  = string
	Strings = []string
	Float   = float32
	Bool    = bool
)

type yySymType struct {
	yys int
	// Common
	String
	Strings
	Int
	Float
	Bool
	Time
	// Combat log
	Damage
	DamageModifiers
	Object
	Heal
	Kill
	Participant
	ParticipationModifiers
	ConnectToGameSession
	Start
	Finished
	Reward
	LogLine
}

const INT = 57346
const STRING = 57347
const TIME = 57348
const COMBAT = 57349
const ARROW = 57350
const FLOAT = 57351
const SOURCE = 57352
const FRIENDLY_FIRE = 57353
const DAMAGE = 57354
const DAMAGE_MODIFIER = 57355
const ROCKET = 57356
const HEAL = 57357
const KILL = 57358
const PARTICIPANT = 57359
const PARTICIPATION_MODIFIER = 57360
const PARTICIPATION_MODIFIERS_END = 57361
const CONNECT_TO_GAME_SESSION_PREFIX = 57362
const START = 57363
const GAMEPLAY_FINISHED = 57364
const REWARD = 57365
const EOL = 57366

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"INT",
	"STRING",
	"TIME",
	"COMBAT",
	"ARROW",
	"FLOAT",
	"SOURCE",
	"FRIENDLY_FIRE",
	"DAMAGE",
	"DAMAGE_MODIFIER",
	"ROCKET",
	"HEAL",
	"KILL",
	"PARTICIPANT",
	"PARTICIPATION_MODIFIER",
	"PARTICIPATION_MODIFIERS_END",
	"CONNECT_TO_GAME_SESSION_PREFIX",
	"START",
	"GAMEPLAY_FINISHED",
	"REWARD",
	"EOL",
	"'|'",
	"'('",
	"')'",
	"';'",
	"'\\t'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 90

var yyAct = [...]int8{
	70, 59, 22, 34, 35, 13, 57, 38, 14, 15,
	16, 37, 71, 20, 17, 18, 19, 24, 27, 34,
	35, 68, 21, 71, 84, 76, 82, 85, 80, 71,
	72, 73, 60, 69, 62, 67, 45, 65, 58, 48,
	49, 50, 56, 52, 36, 33, 3, 2, 75, 66,
	54, 53, 23, 47, 44, 42, 41, 40, 31, 29,
	28, 26, 74, 86, 77, 64, 55, 46, 32, 30,
	1, 4, 43, 11, 10, 9, 63, 12, 78, 61,
	81, 51, 8, 39, 7, 6, 83, 79, 5, 25,
}

var yyPact = [...]int16{
	41, -1000, 39, -7, -2, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 47, 47, 56, 55, 54, 65, 53,
	64, -1000, 37, -6, 36, -17, -22, -1000, 52, 51,
	50, 49, -1000, 47, 63, 48, 47, 47, 47, 34,
	-1000, 46, 45, 62, -1000, 33, -1000, -21, 29, 22,
	-1000, -1000, 24, 61, 28, 44, 26, -4, 23, 18,
	-1000, 12, -1000, -1000, -1000, -1000, 43, 16, 60, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 22, -1000, 15, 1,
	-1000, 10, 14, -1000, 59, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 2, 89, 1, 88, 87, 0, 86, 85, 84,
	83, 82, 81, 79, 77, 76, 75, 74, 73, 72,
	71, 70,
}

var yyR1 = [...]int8{
	0, 21, 20, 20, 20, 20, 20, 20, 20, 20,
	1, 1, 6, 6, 7, 7, 3, 3, 4, 5,
	5, 8, 9, 2, 2, 13, 13, 13, 10, 10,
	11, 12, 12, 15, 15, 16, 14, 17, 19, 19,
	18,
}

var yyR2 = [...]int8{
	0, 4, 1, 1, 1, 1, 1, 1, 1, 1,
	3, 6, 1, 0, 2, 0, 1, 0, 11, 1,
	3, 6, 6, 3, 1, 2, 2, 0, 1, 0,
	6, 2, 0, 1, 0, 5, 2, 5, 1, 0,
	6,
}

var yyChk = [...]int16{
	-1000, -21, 6, 7, -20, -4, -8, -9, -11, -16,
	-17, -18, -14, 12, 15, 16, 17, 21, 22, 23,
	20, 24, -1, 5, -1, -2, 5, -1, 5, 5,
	4, 5, 4, 8, 25, 26, 8, 28, 29, -10,
	5, 5, 5, -19, 5, -1, 4, 5, -1, -1,
	-1, -12, 9, 5, 5, 4, 9, 27, 9, -3,
	10, -13, 10, -15, 4, 9, 5, 9, 25, 10,
	-6, 11, 18, 19, -6, 5, 9, 4, -3, -5,
	13, -6, 25, -7, 14, 13, 4,
}

var yyDef = [...]int8{
	0, -2, 0, 0, 0, 2, 3, 4, 5, 6,
	7, 8, 9, 0, 0, 0, 0, 0, 0, 0,
	0, 1, 0, 0, 0, 0, 0, 24, 29, 0,
	0, 39, 36, 0, 0, 0, 0, 0, 0, 32,
	28, 0, 0, 0, 38, 0, 10, 0, 0, 17,
	23, 27, 0, 34, 0, 0, 0, 0, 0, 13,
	16, 13, 31, 35, 33, 37, 0, 0, 0, 21,
	22, 12, 25, 26, 30, 40, 17, 11, 0, 13,
	19, 15, 0, 18, 0, 20, 14,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 29,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	26, 27, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 28,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 25,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyDollar[3].LogLine.setTime(yyDollar[1].Time)
			yylex.(*lexer).line = yyDollar[3].LogLine
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.LogLine = &yyDollar[1].Damage
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.LogLine = &yyDollar[1].Heal
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.LogLine = &yyDollar[1].Kill
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.LogLine = &yyDollar[1].Participant
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.LogLine = &yyDollar[1].Start
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.LogLine = &yyDollar[1].Finished
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.LogLine = &yyDollar[1].Reward
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.LogLine = &yyDollar[1].ConnectToGameSession
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.Object = Object{
				Name:     yyDollar[1].String,
				ObjectID: yyDollar[3].Int,
			}
		}
	case 11:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.Object = Object{
				PlayerObject: PlayerObject{
					ObjectName:  yyDollar[1].String,
					ObjectOwner: yyDollar[3].String,
				},
				ObjectID: yyDollar[6].Int,
			}
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Bool = true
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.Bool = false
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Int = yyDollar[2].Int
		}
	case 15:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.Int = 0
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.String = yyDollar[1].String
		}
	case 17:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.String = ""
		}
	case 18:
		yyDollar = yyS[yypt-11 : yypt+1]
		{
			yyVAL.Damage = Damage{
				Initiator:       yyDollar[2].Object,
				Recipient:       yyDollar[4].Object,
				DamageFull:      yyDollar[5].Float,
				DamageHull:      yyDollar[6].Float,
				DamageShield:    yyDollar[7].Float,
				Source:          yyDollar[8].String,
				DamageModifiers: yyDollar[9].DamageModifiers,
				FriendlyFire:    yyDollar[10].Bool,
				Rocket:          yyDollar[11].Int,
			}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.DamageModifiers = []DamageModifier{DamageModifier(yyDollar[1].String)}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.DamageModifiers = append(yyVAL.DamageModifiers, DamageModifier(yyDollar[3].String))
		}
	case 21:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.Heal = Heal{
				Initiator: yyDollar[2].Object,
				Recipient: yyDollar[4].Object,
				Heal:      yyDollar[5].Float,
				Source:    yyDollar[6].String,
			}
		}
	case 22:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.Kill = Kill{
				Killed:       yyDollar[2].Object,
				Killer:       yyDollar[4].Object,
				Source:       yyDollar[5].String,
				FriendlyFire: yyDollar[6].Bool,
			}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.Object = Object{
				Name: yyDollar[1].String,
				PlayerObject: PlayerObject{
					ObjectName: yyDollar[3].Object.Name,
				},
				ObjectID: yyDollar[3].Object.ObjectID,
			}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Object = yyDollar[1].Object
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.ParticipationModifiers = append(yyDollar[1].ParticipationModifiers, ParticipationModifier(yyDollar[2].String))
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.ParticipationModifiers = yyDollar[1].ParticipationModifiers
		}
	case 27:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.ParticipationModifiers = nil
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.String = yyDollar[1].String
		}
	case 29:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.String = ""
		}
	case 30:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.Participant = Participant{
				Name:           yyDollar[2].String,
				Ship:           yyDollar[3].String,
				Damage:         yyDollar[4].Participant.Damage,
				MostDamageWith: yyDollar[4].Participant.MostDamageWith,
				Modifiers:      yyDollar[5].ParticipationModifiers,
				FriendlyFire:   yyDollar[6].Bool,
			}
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.Participant.Damage = yyDollar[1].Float
			yyVAL.Participant.MostDamageWith = yyDollar[2].String
		}
	case 32:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.Participant.Damage = 0
			yyVAL.Participant.MostDamageWith = ""
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.Int = yyDollar[1].Int
		}
	case 34:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.Int = 0
		}
	case 35:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.Start = Start{
				What:              yyDollar[2].String,
				GameMode:          yyDollar[3].String,
				MapName:           yyDollar[4].String,
				LocalClientTeamID: yyDollar[5].Int,
			}
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.ConnectToGameSession.SessionID = yyDollar[2].Int
		}
	case 37:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.Finished = Finished{
				WinnerTeamID: yyDollar[2].Int,
				WinReason:    yyDollar[3].String,
				FinishReason: yyDollar[4].String,
				GameTime:     yyDollar[5].Float,
			}
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.String = yyDollar[1].String
		}
	case 39:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.String = ""
		}
	case 40:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.Reward = Reward{
				Recipient:  yyDollar[2].String,
				Ship:       yyDollar[3].String,
				Reward:     yyDollar[4].Int,
				RewardType: yyDollar[5].String,
				Reason:     yyDollar[6].String,
			}
		}
	}
	goto yystack /* stack new state and value */
}
