// Code generated by goyacc -v internal/parser/combat/ext/y.output -l -p Yacc -o internal/parser/combat/lexer.gen.go internal/parser/combat/ext/lexer.y. DO NOT EDIT.
package combat

import __yyfmt__ "fmt"

import (
	"fmt"
)

type Lexer struct {
	line LogLine

	pos    int
	tokens []Token
	err    error
}

func (l *Lexer) Init(toks []Token) {
	l.pos = 0
	l.tokens = toks
	l.err = nil
	l.line = nil
}

func (l *Lexer) Lex(out *YaccSymType) int {
	if l.pos >= len(l.tokens) {
		return 0
	}
	t := l.tokens[l.pos]
	l.pos++
	t.set(out)
	return t.token()
}

func (l *Lexer) Error(errMsg string) {
	l.err = fmt.Errorf("lexer error: %s", errMsg)
}

func (l *Lexer) Res() (LogLine, error) {
	return l.line, l.err
}

func (y *YaccParserImpl) New() *YaccParserImpl {
	return &YaccParserImpl{}
}

type YaccSymType struct {
	yys int
	any
	string
	strArr
	int
	float32
	bool
	ParticipationModifiers
	Spell
}

const INT = 57346
const STRING = 57347
const TIME = 57348
const COMBAT = 57349
const ARROW = 57350
const FLOAT = 57351
const SOURCE = 57352
const FRIENDLY_FIRE = 57353
const DAMAGE = 57354
const DAMAGE_MODIFIER = 57355
const ROCKET = 57356
const HEAL = 57357
const KILL = 57358
const PARTICIPANT = 57359
const PARTICIPATION_MODIFIER = 57360
const PARTICIPATION_MODIFIERS_END = 57361
const CONNECT_TO_GAME_SESSION_PREFIX = 57362
const SPAWN_PREFIX = 57363
const SPELL_PREFIX = 57364
const SPELL_NORMALIZER = 57365
const SPELL_GODGIFT = 57366
const START = 57367
const GAMEPLAY_FINISHED = 57368
const REWARD = 57369
const EOL = 57370

var YaccToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"INT",
	"STRING",
	"TIME",
	"COMBAT",
	"ARROW",
	"FLOAT",
	"SOURCE",
	"FRIENDLY_FIRE",
	"DAMAGE",
	"DAMAGE_MODIFIER",
	"ROCKET",
	"HEAL",
	"KILL",
	"PARTICIPANT",
	"PARTICIPATION_MODIFIER",
	"PARTICIPATION_MODIFIERS_END",
	"CONNECT_TO_GAME_SESSION_PREFIX",
	"SPAWN_PREFIX",
	"SPELL_PREFIX",
	"SPELL_NORMALIZER",
	"SPELL_GODGIFT",
	"START",
	"GAMEPLAY_FINISHED",
	"REWARD",
	"EOL",
	"'|'",
	"'('",
	"')'",
	"';'",
	"'\\t'",
}

var YaccStatenames = [...]string{}

const YaccEofCode = 1
const YaccErrCode = 2
const YaccInitialStackSize = 16

var YaccExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 38,
	28, 41,
	-2, 46,
}

const YaccPrivate = 57344

const YaccLast = 103

var YaccAct = [...]int8{
	83, 72, 26, 15, 45, 70, 16, 17, 18, 42,
	43, 22, 23, 24, 84, 81, 19, 20, 21, 28,
	31, 42, 43, 25, 97, 46, 84, 39, 40, 98,
	93, 84, 95, 85, 86, 73, 82, 75, 89, 80,
	78, 71, 69, 63, 56, 44, 41, 59, 60, 61,
	3, 2, 88, 79, 68, 67, 65, 64, 27, 58,
	52, 50, 49, 48, 37, 35, 33, 32, 30, 99,
	90, 77, 66, 57, 55, 87, 53, 36, 34, 1,
	4, 51, 11, 10, 9, 54, 38, 14, 13, 76,
	12, 91, 74, 94, 62, 8, 47, 7, 6, 96,
	92, 5, 29,
}

var YaccPact = [...]int16{
	45, -1000, 43, -9, -5, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 53, 53, 63, 62, 61,
	74, 60, 73, 59, 4, -1000, 38, -20, 37, -28,
	-8, -1000, 58, 57, 56, 55, -1000, 72, -1000, 70,
	-1000, 53, 69, 54, 53, 53, 53, 34, -1000, 52,
	51, 68, -1000, 50, 49, -1000, 33, -1000, -26, 32,
	25, -1000, -1000, 27, 67, 31, 48, -1000, -1000, 30,
	-14, 26, 20, -1000, 15, -1000, -1000, -1000, -1000, 47,
	29, 66, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 25,
	-1000, 17, 3, -1000, 10, 16, -1000, 65, -1000, -1000,
}

var YaccPgo = [...]int8{
	0, 2, 102, 1, 101, 100, 0, 99, 98, 97,
	96, 95, 94, 92, 90, 89, 88, 87, 86, 85,
	84, 83, 82, 81, 80, 79,
}

var YaccR1 = [...]int8{
	0, 25, 24, 24, 24, 24, 24, 24, 24, 24,
	24, 24, 1, 1, 6, 6, 7, 7, 3, 3,
	4, 5, 5, 8, 9, 2, 2, 13, 13, 13,
	10, 10, 11, 12, 12, 15, 15, 20, 14, 16,
	17, 17, 18, 18, 18, 19, 19, 21, 23, 23,
	22,
}

var YaccR2 = [...]int8{
	0, 4, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 3, 6, 1, 0, 2, 0, 1, 0,
	11, 1, 3, 6, 6, 3, 1, 2, 2, 0,
	1, 0, 6, 2, 0, 1, 0, 5, 2, 4,
	3, 2, 2, 1, 0, 2, 0, 5, 1, 0,
	6,
}

var YaccChk = [...]int16{
	-1000, -25, 6, 7, -24, -4, -8, -9, -11, -20,
	-21, -22, -14, -16, -17, 12, 15, 16, 17, 25,
	26, 27, 20, 21, 22, 28, -1, 5, -1, -2,
	5, -1, 5, 5, 4, 5, 4, 5, -18, 23,
	24, 8, 29, 30, 8, 32, 33, -10, 5, 5,
	5, -23, 5, 4, -19, 4, -1, 4, 5, -1,
	-1, -1, -12, 9, 5, 5, 4, 5, 5, 9,
	31, 9, -3, 10, -13, 10, -15, 4, 9, 5,
	9, 29, 10, -6, 11, 18, 19, -6, 5, 9,
	4, -3, -5, 13, -6, 29, -7, 14, 13, 4,
}

var YaccDef = [...]int8{
	0, -2, 0, 0, 0, 2, 3, 4, 5, 6,
	7, 8, 9, 10, 11, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 44, 1, 0, 0, 0, 0,
	0, 26, 31, 0, 0, 49, 38, 0, -2, 0,
	43, 0, 0, 0, 0, 0, 0, 34, 30, 0,
	0, 0, 48, 0, 40, 42, 0, 12, 0, 0,
	19, 25, 29, 0, 36, 0, 0, 39, 45, 0,
	0, 0, 15, 18, 15, 33, 37, 35, 47, 0,
	0, 0, 23, 24, 14, 27, 28, 32, 50, 19,
	13, 0, 15, 21, 17, 0, 20, 0, 22, 16,
}

var YaccTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 33,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	30, 31, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 32,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 29,
}

var YaccTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28,
}

var YaccTok3 = [...]int8{
	0,
}

var YaccErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	YaccDebug        = 0
	YaccErrorVerbose = false
)

type YaccLexer interface {
	Lex(lval *YaccSymType) int
	Error(s string)
}

type YaccParser interface {
	Parse(YaccLexer) int
	Lookahead() int
}

type YaccParserImpl struct {
	lval  YaccSymType
	stack [YaccInitialStackSize]YaccSymType
	char  int
}

func (p *YaccParserImpl) Lookahead() int {
	return p.char
}

func YaccNewParser() YaccParser {
	return &YaccParserImpl{}
}

const YaccFlag = -1000

func YaccTokname(c int) string {
	if c >= 1 && c-1 < len(YaccToknames) {
		if YaccToknames[c-1] != "" {
			return YaccToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func YaccStatname(s int) string {
	if s >= 0 && s < len(YaccStatenames) {
		if YaccStatenames[s] != "" {
			return YaccStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func YaccErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !YaccErrorVerbose {
		return "syntax error"
	}

	for _, e := range YaccErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + YaccTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(YaccPact[state])
	for tok := TOKSTART; tok-1 < len(YaccToknames); tok++ {
		if n := base + tok; n >= 0 && n < YaccLast && int(YaccChk[int(YaccAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if YaccDef[state] == -2 {
		i := 0
		for YaccExca[i] != -1 || int(YaccExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; YaccExca[i] >= 0; i += 2 {
			tok := int(YaccExca[i])
			if tok < TOKSTART || YaccExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if YaccExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += YaccTokname(tok)
	}
	return res
}

func Yacclex1(lex YaccLexer, lval *YaccSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(YaccTok1[0])
		goto out
	}
	if char < len(YaccTok1) {
		token = int(YaccTok1[char])
		goto out
	}
	if char >= YaccPrivate {
		if char < YaccPrivate+len(YaccTok2) {
			token = int(YaccTok2[char-YaccPrivate])
			goto out
		}
	}
	for i := 0; i < len(YaccTok3); i += 2 {
		token = int(YaccTok3[i+0])
		if token == char {
			token = int(YaccTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(YaccTok2[1]) /* unknown char */
	}
	if YaccDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", YaccTokname(token), uint(char))
	}
	return char, token
}

func YaccParse(Yacclex YaccLexer) int {
	return YaccNewParser().Parse(Yacclex)
}

func (Yaccrcvr *YaccParserImpl) Parse(Yacclex YaccLexer) int {
	var Yaccn int
	var YaccVAL YaccSymType
	var YaccDollar []YaccSymType
	_ = YaccDollar // silence set and not used
	YaccS := Yaccrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Yaccstate := 0
	Yaccrcvr.char = -1
	Yacctoken := -1 // Yaccrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Yaccstate = -1
		Yaccrcvr.char = -1
		Yacctoken = -1
	}()
	Yaccp := -1
	goto Yaccstack

ret0:
	return 0

ret1:
	return 1

Yaccstack:
	/* put a state and value onto the stack */
	if YaccDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", YaccTokname(Yacctoken), YaccStatname(Yaccstate))
	}

	Yaccp++
	if Yaccp >= len(YaccS) {
		nyys := make([]YaccSymType, len(YaccS)*2)
		copy(nyys, YaccS)
		YaccS = nyys
	}
	YaccS[Yaccp] = YaccVAL
	YaccS[Yaccp].yys = Yaccstate

Yaccnewstate:
	Yaccn = int(YaccPact[Yaccstate])
	if Yaccn <= YaccFlag {
		goto Yaccdefault /* simple state */
	}
	if Yaccrcvr.char < 0 {
		Yaccrcvr.char, Yacctoken = Yacclex1(Yacclex, &Yaccrcvr.lval)
	}
	Yaccn += Yacctoken
	if Yaccn < 0 || Yaccn >= YaccLast {
		goto Yaccdefault
	}
	Yaccn = int(YaccAct[Yaccn])
	if int(YaccChk[Yaccn]) == Yacctoken { /* valid shift */
		Yaccrcvr.char = -1
		Yacctoken = -1
		YaccVAL = Yaccrcvr.lval
		Yaccstate = Yaccn
		if Errflag > 0 {
			Errflag--
		}
		goto Yaccstack
	}

Yaccdefault:
	/* default state action */
	Yaccn = int(YaccDef[Yaccstate])
	if Yaccn == -2 {
		if Yaccrcvr.char < 0 {
			Yaccrcvr.char, Yacctoken = Yacclex1(Yacclex, &Yaccrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if YaccExca[xi+0] == -1 && int(YaccExca[xi+1]) == Yaccstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Yaccn = int(YaccExca[xi+0])
			if Yaccn < 0 || Yaccn == Yacctoken {
				break
			}
		}
		Yaccn = int(YaccExca[xi+1])
		if Yaccn < 0 {
			goto ret0
		}
	}
	if Yaccn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Yacclex.Error(YaccErrorMessage(Yaccstate, Yacctoken))
			Nerrs++
			if YaccDebug >= 1 {
				__yyfmt__.Printf("%s", YaccStatname(Yaccstate))
				__yyfmt__.Printf(" saw %s\n", YaccTokname(Yacctoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Yaccp >= 0 {
				Yaccn = int(YaccPact[YaccS[Yaccp].yys]) + YaccErrCode
				if Yaccn >= 0 && Yaccn < YaccLast {
					Yaccstate = int(YaccAct[Yaccn]) /* simulate a shift of "error" */
					if int(YaccChk[Yaccstate]) == YaccErrCode {
						goto Yaccstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if YaccDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", YaccS[Yaccp].yys)
				}
				Yaccp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if YaccDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", YaccTokname(Yacctoken))
			}
			if Yacctoken == YaccEofCode {
				goto ret1
			}
			Yaccrcvr.char = -1
			Yacctoken = -1
			goto Yaccnewstate /* try again in the same state */
		}
	}

	/* reduction by production Yaccn */
	if YaccDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Yaccn, YaccStatname(Yaccstate))
	}

	Yaccnt := Yaccn
	Yaccpt := Yaccp
	_ = Yaccpt // guard against "declared and not used"

	Yaccp -= int(YaccR2[Yaccn])
	// Yaccp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Yaccp+1 >= len(YaccS) {
		nyys := make([]YaccSymType, len(YaccS)*2)
		copy(nyys, YaccS)
		YaccS = nyys
	}
	YaccVAL = YaccS[Yaccp+1]

	/* consult goto table to find next state */
	Yaccn = int(YaccR1[Yaccn])
	Yaccg := int(YaccPgo[Yaccn])
	Yaccj := Yaccg + YaccS[Yaccp].yys + 1

	if Yaccj >= YaccLast {
		Yaccstate = int(YaccAct[Yaccg])
	} else {
		Yaccstate = int(YaccAct[Yaccj])
		if int(YaccChk[Yaccstate]) != -Yaccn {
			Yaccstate = int(YaccAct[Yaccg])
		}
	}
	// dummy call; replaced with literal code
	switch Yaccnt {

	case 1:
		YaccDollar = YaccS[Yaccpt-4 : Yaccpt+1]
		{
			ll := YaccDollar[3].any.(LogLine)
			ll.setTime(YaccDollar[1].string)
			Yacclex.(*Lexer).line = ll
		}
	case 2:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.any = YaccDollar[1].any
		}
	case 3:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.any = YaccDollar[1].any
		}
	case 4:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.any = YaccDollar[1].any
		}
	case 5:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.any = YaccDollar[1].any
		}
	case 6:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.any = YaccDollar[1].any
		}
	case 7:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.any = YaccDollar[1].any
		}
	case 8:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.any = YaccDollar[1].any
		}
	case 9:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.any = YaccDollar[1].any
		}
	case 10:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.any = YaccDollar[1].any
		}
	case 11:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.any = YaccDollar[1].any
		}
	case 12:
		YaccDollar = YaccS[Yaccpt-3 : Yaccpt+1]
		{
			YaccVAL.any = &Object{
				Name:     YaccDollar[1].string,
				ObjectID: YaccDollar[3].int,
			}
		}
	case 13:
		YaccDollar = YaccS[Yaccpt-6 : Yaccpt+1]
		{
			YaccVAL.any = &Object{
				PlayerObject: PlayerObject{
					ObjectName:  YaccDollar[1].string,
					ObjectOwner: YaccDollar[3].string,
				},
				ObjectID: YaccDollar[6].int,
			}
		}
	case 14:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.bool = true
		}
	case 15:
		YaccDollar = YaccS[Yaccpt-0 : Yaccpt+1]
		{
			YaccVAL.bool = false
		}
	case 16:
		YaccDollar = YaccS[Yaccpt-2 : Yaccpt+1]
		{
			YaccVAL.int = YaccDollar[2].int
		}
	case 17:
		YaccDollar = YaccS[Yaccpt-0 : Yaccpt+1]
		{
			YaccVAL.int = 0
		}
	case 18:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.string = YaccDollar[1].string
		}
	case 19:
		YaccDollar = YaccS[Yaccpt-0 : Yaccpt+1]
		{
			YaccVAL.string = ""
		}
	case 20:
		YaccDollar = YaccS[Yaccpt-11 : Yaccpt+1]
		{
			YaccVAL.any = &Damage{
				Initiator:       *YaccDollar[2].any.(*Object),
				Recipient:       *YaccDollar[4].any.(*Object),
				DamageFull:      YaccDollar[5].float32,
				DamageHull:      YaccDollar[6].float32,
				DamageShield:    YaccDollar[7].float32,
				Source:          YaccDollar[8].string,
				DamageModifiers: YaccDollar[9].any.([]DamageModifier),
				FriendlyFire:    YaccDollar[10].bool,
				Rocket:          YaccDollar[11].int,
			}
		}
	case 21:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.any = []DamageModifier{DamageModifier(YaccDollar[1].string)}
		}
	case 22:
		YaccDollar = YaccS[Yaccpt-3 : Yaccpt+1]
		{
			YaccVAL.any = append(YaccVAL.any.([]DamageModifier), DamageModifier(YaccDollar[3].string))
		}
	case 23:
		YaccDollar = YaccS[Yaccpt-6 : Yaccpt+1]
		{
			YaccVAL.any = &Heal{
				Initiator: *YaccDollar[2].any.(*Object),
				Recipient: *YaccDollar[4].any.(*Object),
				Heal:      YaccDollar[5].float32,
				Source:    YaccDollar[6].string,
			}
		}
	case 24:
		YaccDollar = YaccS[Yaccpt-6 : Yaccpt+1]
		{
			YaccVAL.any = &Kill{
				Killed:       *YaccDollar[2].any.(*Object),
				Killer:       *YaccDollar[4].any.(*Object),
				Source:       YaccDollar[5].string,
				FriendlyFire: YaccDollar[6].bool,
			}
		}
	case 25:
		YaccDollar = YaccS[Yaccpt-3 : Yaccpt+1]
		{
			YaccVAL.any = &Object{
				Name: YaccDollar[1].string,
				PlayerObject: PlayerObject{
					ObjectName: YaccDollar[3].any.(*Object).Name,
				},
				ObjectID: YaccDollar[3].any.(*Object).ObjectID,
			}
		}
	case 26:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.any = YaccDollar[1].any
		}
	case 27:
		YaccDollar = YaccS[Yaccpt-2 : Yaccpt+1]
		{
			YaccVAL.ParticipationModifiers = append(YaccDollar[1].ParticipationModifiers, ParticipationModifier(YaccDollar[2].string))
		}
	case 28:
		YaccDollar = YaccS[Yaccpt-2 : Yaccpt+1]
		{
			YaccVAL.ParticipationModifiers = YaccDollar[1].ParticipationModifiers
		}
	case 29:
		YaccDollar = YaccS[Yaccpt-0 : Yaccpt+1]
		{
			YaccVAL.ParticipationModifiers = nil
		}
	case 30:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.string = YaccDollar[1].string
		}
	case 31:
		YaccDollar = YaccS[Yaccpt-0 : Yaccpt+1]
		{
			YaccVAL.string = ""
		}
	case 32:
		YaccDollar = YaccS[Yaccpt-6 : Yaccpt+1]
		{
			YaccVAL.any = &Participant{
				Name:           YaccDollar[2].string,
				Ship:           YaccDollar[3].string,
				Damage:         YaccDollar[4].any.([]any)[0].(float32),
				MostDamageWith: YaccDollar[4].any.([]any)[1].(string),
				Modifiers:      YaccDollar[5].ParticipationModifiers,
				FriendlyFire:   YaccDollar[6].bool,
			}
		}
	case 33:
		YaccDollar = YaccS[Yaccpt-2 : Yaccpt+1]
		{
			YaccVAL.any = []any{YaccDollar[1].float32, YaccDollar[2].string}
		}
	case 34:
		YaccDollar = YaccS[Yaccpt-0 : Yaccpt+1]
		{
			YaccVAL.any = []any{float32(0), ""}
		}
	case 35:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.int = YaccDollar[1].int
		}
	case 36:
		YaccDollar = YaccS[Yaccpt-0 : Yaccpt+1]
		{
			YaccVAL.int = 0
		}
	case 37:
		YaccDollar = YaccS[Yaccpt-5 : Yaccpt+1]
		{
			YaccVAL.any = &Start{
				What:              YaccDollar[2].string,
				GameMode:          YaccDollar[3].string,
				MapName:           YaccDollar[4].string,
				LocalClientTeamID: YaccDollar[5].int,
			}
		}
	case 38:
		YaccDollar = YaccS[Yaccpt-2 : Yaccpt+1]
		{
			YaccVAL.any = &ConnectToGameSession{
				SessionID: YaccDollar[2].int,
			}
		}
	case 39:
		YaccDollar = YaccS[Yaccpt-4 : Yaccpt+1]
		{
			YaccVAL.any = &Spawn{
				Name: YaccDollar[2].string,
				ID:   YaccDollar[3].int,
				Ship: YaccDollar[4].string,
			}
		}
	case 40:
		YaccDollar = YaccS[Yaccpt-3 : Yaccpt+1]
		{
			YaccVAL.any = &Spell{
				Normalizer: YaccDollar[2].Spell.Normalizer,
				GodGift:    YaccDollar[2].Spell.GodGift,
				Targets:    YaccDollar[3].strArr,
			}
		}
	case 41:
		YaccDollar = YaccS[Yaccpt-2 : Yaccpt+1]
		{
			YaccVAL.any = &Spell{}
		}
	case 42:
		YaccDollar = YaccS[Yaccpt-2 : Yaccpt+1]
		{
			YaccVAL.Spell.Normalizer = YaccDollar[2].int
		}
	case 43:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.Spell.GodGift = true
		}
	case 44:
		YaccDollar = YaccS[Yaccpt-0 : Yaccpt+1]
		{
		}
	case 45:
		YaccDollar = YaccS[Yaccpt-2 : Yaccpt+1]
		{
			YaccVAL.strArr = append(YaccVAL.strArr, YaccDollar[2].string)
		}
	case 46:
		YaccDollar = YaccS[Yaccpt-0 : Yaccpt+1]
		{
		}
	case 47:
		YaccDollar = YaccS[Yaccpt-5 : Yaccpt+1]
		{
			YaccVAL.any = &Finished{
				WinnerTeamID: YaccDollar[2].int,
				WinReason:    YaccDollar[3].string,
				FinishReason: YaccDollar[4].string,
				GameTime:     YaccDollar[5].float32,
			}
		}
	case 48:
		YaccDollar = YaccS[Yaccpt-1 : Yaccpt+1]
		{
			YaccVAL.string = YaccDollar[1].string
		}
	case 49:
		YaccDollar = YaccS[Yaccpt-0 : Yaccpt+1]
		{
			YaccVAL.string = ""
		}
	case 50:
		YaccDollar = YaccS[Yaccpt-6 : Yaccpt+1]
		{
			YaccVAL.any = &Reward{
				Recipient:  YaccDollar[2].string,
				Ship:       YaccDollar[3].string,
				Reward:     YaccDollar[4].int,
				RewardType: YaccDollar[5].string,
				Reason:     YaccDollar[6].string,
			}
		}
	}
	goto Yaccstack /* stack new state and value */
}
