// Code generated by goyacc -o data.go ./dmg.y. DO NOT EDIT.

//line ./dmg.y:2
package main

import __yyfmt__ "fmt"

//line ./dmg.y:2

import "time"

type LogLine[T any] struct {
	LogTime time.Time
	Line    T
}

type CombatLine struct {
	Damage *Damage
}

type Damage struct {
	Initiator Object
	Recipient Object
	Reason    string

	DamageFull      float32
	DamageHull      float32
	DamageShield    float32
	DamageModifiers DamageModifiersMap

	FriendlyFire bool
}

type PlayerObject struct {
	ObjectName  string
	ObjectOwner string
}

type Object struct {
	Name string
	PlayerObject
	ObjectID int
}

type DamageModifier string
type DamageModifiersMap map[DamageModifier]struct{}

// TODO string to enum 1 << iota
const (
	DamageTypeEMP         DamageModifier = "EMP"
	DamageTypeKinetic     DamageModifier = "KINETIC"
	DamageTypeThermal     DamageModifier = "THERMAL"
	DamageTypeTrueDamage  DamageModifier = "TRUE_DAMAGE"
	DamageUnintention     DamageModifier = "UNINTENTION"
	DamageCrit            DamageModifier = "CRIT"
	DamageExplosion       DamageModifier = "EXPLOSION"
	DamageCollision       DamageModifier = "COLLISION"
	DamageWeaponPrimary   DamageModifier = "PRIMARY_WEAPON"
	DamageWeaponSecondary DamageModifier = "SECONDARY_WEAPON"
	DamageIgnoreScale     DamageModifier = "IGNORE_DAMAGE_SCALE"
	DamageIgnoreShield    DamageModifier = "IGNORE_SHIELD"
	DamageModule          DamageModifier = "MODULE"
)

type damageSucks struct {
	Source    string
	Modifiers DamageModifiersMap
}

//line ./dmg.y:66
type yySymType struct {
	yys    int
	String string
	Int    int
	Float  float32
	Bool   bool

	Time time.Time

	CombatLine         *LogLine[*CombatLine]
	CombatLines        []*LogLine[*CombatLine]
	Combat             *CombatLine
	Damage             *Damage
	DamageSucks        damageSucks
	DamageModifiersMap DamageModifiersMap
	Object             Object
}

const ARROW = 57346
const DAMAGE = 57347
const COMBAT = 57348
const EOL = 57349
const LBRACE = 57350
const RBRACE = 57351
const VSLASH = 57352
const DAMAGE_HULL_START = 57353
const DAMAGE_SHIELD_START = 57354
const FLOAT = 57355
const INT = 57356
const STRING = 57357
const FRIENDLY_FIRE = 57358
const TIME = 57359

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ARROW",
	"DAMAGE",
	"COMBAT",
	"EOL",
	"LBRACE",
	"RBRACE",
	"VSLASH",
	"DAMAGE_HULL_START",
	"DAMAGE_SHIELD_START",
	"FLOAT",
	"INT",
	"STRING",
	"FRIENDLY_FIRE",
	"TIME",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line ./dmg.y:176

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 33,
	15, 12,
	-2, 14,
}

const yyPrivate = 57344

const yyLast = 43

var yyAct = [...]int8{
	32, 4, 5, 36, 41, 34, 40, 38, 19, 12,
	13, 5, 33, 25, 18, 28, 26, 20, 27, 24,
	16, 39, 15, 23, 17, 42, 29, 21, 22, 9,
	8, 10, 37, 14, 3, 1, 30, 6, 31, 35,
	11, 7, 2,
}

var yyPact = [...]int16{
	-6, -1000, -15, -1000, -1000, 24, -1000, 22, 26, -1000,
	-5, -1000, 29, 12, -5, 0, -7, 4, -1000, 18,
	20, 13, 8, -1, 3, -1000, 6, 2, 17, -3,
	-13, -8, 11, -1000, -9, -1000, -1000, 11, -1000, -11,
	16, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 42, 34, 41, 40, 9, 39, 0, 38, 36,
	35,
}

var yyR1 = [...]int8{
	0, 10, 1, 1, 1, 2, 3, 4, 5, 5,
	9, 9, 8, 8, 7, 7, 6, 6,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 1, 3, 3, 12, 3, 6,
	2, 1, 1, 3, 1, 3, 1, 0,
}

var yyChk = [...]int16{
	-1000, -10, -1, -2, 7, 17, -2, -3, 6, 7,
	5, -4, -5, 15, 4, 10, 8, -5, 14, 15,
	13, 9, 8, 10, 11, 14, 13, 12, 13, 9,
	-9, -8, -7, 15, 8, -6, 16, -7, 15, 10,
	15, 15, 9,
}

var yyDef = [...]int8{
	0, -2, 1, 3, 4, 0, 2, 0, 0, 5,
	0, 6, 0, 0, 0, 0, 0, 0, 8, 0,
	0, 0, 0, 0, 0, 9, 0, 0, 0, 0,
	17, 0, 11, -2, 0, 7, 16, 10, 14, 0,
	0, 15, 13,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./dmg.y:107
		{
			yylex.(*lexer).res = yyDollar[1].CombatLines
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./dmg.y:111
		{
			yyVAL.CombatLines = append(yyDollar[1].CombatLines, yyDollar[2].CombatLine)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./dmg.y:111
		{
			yyVAL.CombatLines = append(yyVAL.CombatLines, yyDollar[1].CombatLine)
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./dmg.y:111
		{
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./dmg.y:113
		{
			// println($1.String())
			yyVAL.CombatLine = &LogLine[*CombatLine]{
				LogTime: yyDollar[1].Time,
				Line:    yyDollar[2].Combat,
			}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./dmg.y:121
		{
			yyVAL.Combat = &CombatLine{
				Damage: yyDollar[3].Damage,
			}
		}
	case 7:
		yyDollar = yyS[yypt-12 : yypt+1]
//line ./dmg.y:128
		{
			yyVAL.Damage = &Damage{
				Initiator:       yyDollar[1].Object,
				Recipient:       yyDollar[3].Object,
				DamageFull:      yyDollar[4].Float,
				DamageHull:      yyDollar[7].Float,
				DamageShield:    yyDollar[9].Float,
				Reason:          yyDollar[11].DamageSucks.Source,
				DamageModifiers: yyDollar[11].DamageSucks.Modifiers,
				FriendlyFire:    yyDollar[12].Bool,
			}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./dmg.y:141
		{
			yyVAL.Object = Object{
				Name:     yyDollar[1].String,
				ObjectID: yyDollar[3].Int,
			}
		}
	case 9:
		yyDollar = yyS[yypt-6 : yypt+1]
//line ./dmg.y:147
		{
			yyVAL.Object = Object{
				PlayerObject: PlayerObject{
					ObjectName:  yyDollar[1].String,
					ObjectOwner: yyDollar[3].String,
				},
				ObjectID: yyDollar[6].Int,
			}
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line ./dmg.y:157
		{
			yyVAL.DamageSucks.Source = yyDollar[1].String
			yyVAL.DamageSucks.Modifiers = yyDollar[2].DamageModifiersMap
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./dmg.y:160
		{
			yyVAL.DamageSucks.Modifiers = yyDollar[1].DamageModifiersMap
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./dmg.y:164
		{
			yyVAL.String = yyDollar[1].String
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./dmg.y:164
		{
			yyVAL.String = yyDollar[2].String
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./dmg.y:166
		{
			yyVAL.DamageModifiersMap = DamageModifiersMap{
				DamageModifier(yyDollar[1].String): {},
			}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line ./dmg.y:170
		{
			yyVAL.DamageModifiersMap[DamageModifier(yyDollar[3].String)] = struct{}{}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line ./dmg.y:174
		{
			yyVAL.Bool = true
		}
	case 17:
		yyDollar = yyS[yypt-0 : yypt+1]
//line ./dmg.y:174
		{
		}
	}
	goto yystack /* stack new state and value */
}
