// Code generated by goyacc -o parser.go gramma.y. DO NOT EDIT.

//line gramma.y:2
package main

import __yyfmt__ "fmt"

//line gramma.y:2

import (
	"strings"
	"time"
)

type CombatLine struct {
	*Damage
	*Heal
	*Kill
	*Participant
	*ConnectToGameSession
	*Start
	*Finished
	*Reward
}

type ConnectToGameSession struct {
	Time      time.Time
	SessionID int
}

type Start struct {
	Time              time.Time
	What              string
	GameMode          string
	MapName           string
	LocalClientTeamID int
}

type Finished struct {
	Time time.Time

	WinnerTeamID int
	WinReason    string
	FinishReason string
	GameTime     float32
}

type Reward struct {
	Time time.Time

	Recipient  string
	Ship       string
	Reward     int
	RewardType string
	Reason     string
}

type Damage struct {
	Time      time.Time
	Initiator Object
	Recipient Object
	Source    string

	DamageFull      float32
	DamageHull      float32
	DamageShield    float32
	DamageModifiers DamageModifiersMap

	FriendlyFire bool
}

type Heal struct {
	Time      time.Time
	Initiator Object
	Recipient Object
	Source    string

	Heal float32
}

type Kill struct {
	Time         time.Time
	Killed       Object
	Killer       Object
	Source       string
	FriendlyFire bool
}

type Participant struct {
	Time           time.Time
	Name           string
	Ship           string
	Damage         float32
	MostDamageWith string
	BuffDebuff
	FriendlyFire bool
}

type BuffDebuff struct {
	IsBuff   bool
	IsDebuff bool
}

type PlayerObject struct {
	ObjectName  string
	ObjectOwner string
}

type Object struct {
	Name string
	PlayerObject
	ObjectID int
}

type DamageModifier string
type DamageModifiersMap map[DamageModifier]struct{}

// TODO string to enum 1 << iota
const (
	DamageTypeEMP         DamageModifier = "EMP"
	DamageTypeKinetic     DamageModifier = "KINETIC"
	DamageTypeThermal     DamageModifier = "THERMAL"
	DamageTypeTrueDamage  DamageModifier = "TRUE_DAMAGE"
	DamageUnintention     DamageModifier = "UNINTENTION"
	DamageCrit            DamageModifier = "CRIT"
	DamageExplosion       DamageModifier = "EXPLOSION"
	DamageCollision       DamageModifier = "COLLISION"
	DamageWeaponPrimary   DamageModifier = "PRIMARY_WEAPON"
	DamageWeaponSecondary DamageModifier = "SECONDARY_WEAPON"
	DamageIgnoreScale     DamageModifier = "IGNORE_DAMAGE_SCALE"
	DamageIgnoreShield    DamageModifier = "IGNORE_SHIELD"
	DamageModule          DamageModifier = "MODULE"
)

type DamageSucks struct {
	Source    string
	Modifiers DamageModifiersMap
}

type KillSucks struct {
	Source       string
	FriendlyFire bool
}

type (
	Int     = int
	String  = string
	Strings = []string
	Float   = float32
	Bool    = bool
	Time    = time.Time
)

//line gramma.y:150
type yySymType struct {
	yys int
	String
	Strings
	Int
	Float
	Bool
	Time
	Damage
	DamageSucks
	DamageModifiersMap
	Object
	Heal
	Kill
	KillSucks
	Participant
	BuffDebuff
	ConnectToGameSession
	Start
	CombatLine
	Finished
	Reward
}

const COMBAT = 57346
const EOL = 57347
const ARROW = 57348
const FLOAT = 57349
const INT = 57350
const STRING = 57351
const FRIENDLY_FIRE = 57352
const TIME = 57353
const DAMAGE = 57354
const DAMAGE_HULL_START = 57355
const DAMAGE_SHIELD_START = 57356
const HEAL = 57357
const KILL = 57358
const PARTICIPANT = 57359
const BUFF = 57360
const DEBUFF = 57361
const CONNECT_TO_GAME_SESSION_PREFIX = 57362
const EQ_DELIM = 57363
const LOCAL_CLIENT_TEAM = 57364
const START = 57365
const GAMEPLAY_FINISHED = 57366
const ACTUAL_GAME_TIME = 57367
const FINISH_REASON = 57368
const REWARD = 57369

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"COMBAT",
	"EOL",
	"ARROW",
	"FLOAT",
	"INT",
	"STRING",
	"FRIENDLY_FIRE",
	"TIME",
	"DAMAGE",
	"DAMAGE_HULL_START",
	"DAMAGE_SHIELD_START",
	"HEAL",
	"KILL",
	"PARTICIPANT",
	"BUFF",
	"DEBUFF",
	"CONNECT_TO_GAME_SESSION_PREFIX",
	"EQ_DELIM",
	"LOCAL_CLIENT_TEAM",
	"START",
	"GAMEPLAY_FINISHED",
	"ACTUAL_GAME_TIME",
	"FINISH_REASON",
	"REWARD",
	"'('",
	"')'",
	"'|'",
	"';'",
	"'\\t'",
	"'\\''",
	"','",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line gramma.y:498

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 112,
	9, 20,
	-2, 48,
	-1, 129,
	9, 21,
	-2, 30,
}

const yyPrivate = 57344

const yyLast = 147

var yyAct = [...]uint8{
	94, 128, 93, 67, 24, 132, 77, 77, 45, 130,
	44, 124, 50, 14, 119, 116, 15, 16, 17, 103,
	27, 31, 22, 102, 19, 20, 76, 70, 21, 137,
	117, 78, 64, 82, 52, 138, 109, 49, 45, 129,
	44, 95, 97, 122, 114, 79, 73, 81, 60, 56,
	88, 121, 63, 41, 54, 65, 140, 139, 96, 71,
	96, 36, 99, 100, 113, 90, 11, 97, 141, 136,
	125, 133, 12, 123, 120, 115, 112, 68, 110, 107,
	84, 89, 87, 86, 25, 83, 75, 69, 66, 62,
	58, 40, 33, 104, 106, 30, 142, 91, 80, 108,
	61, 59, 38, 118, 105, 101, 74, 111, 72, 47,
	43, 57, 55, 53, 51, 48, 46, 42, 34, 13,
	1, 2, 9, 39, 8, 127, 37, 134, 7, 135,
	35, 131, 10, 18, 98, 85, 6, 32, 92, 5,
	28, 4, 26, 126, 3, 23, 29,
}

var yyPact = [...]int16{
	61, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 115, 1, 75, 75, 86, 83, 113, 40,
	94, 82, 33, 112, 104, 10, 111, 103, 110, 6,
	-20, -1000, 109, 2, -1000, 108, 31, 107, 21, 106,
	81, 93, -1000, 75, 92, 80, -1000, 75, -1000, 0,
	75, -1000, 79, -1000, 68, -1000, 78, -1000, -5, 38,
	101, -1000, 17, 99, 77, -1000, -6, -2, -1000, 16,
	90, -1000, 19, 3, 76, 75, 74, -1000, 73, 24,
	72, 52, 89, -1000, 32, 44, 98, -10, -14, 68,
	97, -1000, -1000, 57, -1000, -1000, 70, -1000, 57, -1000,
	-1000, 5, 69, 68, 67, 50, -1000, 15, -1000, 66,
	-18, -3, -1000, 96, -1000, -19, 65, 26, 14, 64,
	-22, 63, 30, -24, -29, 62, 57, 60, -1, -1000,
	4, 36, 34, -1000, -1000, -1, -1000, 59, -1000, -1000,
	88, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 2, 3, 4, 146, 0, 145, 144, 1, 143,
	142, 141, 140, 139, 138, 137, 136, 135, 134, 133,
	132, 131, 130, 128, 126, 124, 123, 122, 121, 120,
}

var yyR1 = [...]int8{
	0, 29, 28, 28, 28, 28, 28, 28, 28, 28,
	28, 7, 11, 13, 16, 20, 23, 25, 27, 2,
	2, 1, 1, 3, 3, 5, 5, 6, 9, 9,
	8, 8, 10, 12, 14, 14, 4, 4, 18, 18,
	15, 17, 17, 21, 21, 22, 19, 24, 26,
}

var yyR2 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 5, 5, 5, 5, 4, 5, 5, 5, 1,
	2, 1, 3, 3, 6, 1, 0, 12, 2, 1,
	1, 3, 5, 6, 2, 1, 3, 1, 1, 1,
	7, 8, 0, 3, 0, 12, 4, 11, 7,
}

var yyChk = [...]int16{
	-1000, -29, -28, -7, -11, -13, -16, -23, -25, -27,
	-20, 5, 11, 4, 12, 15, 16, 17, -19, 23,
	24, 27, 21, -6, -3, 9, -10, -3, -12, -4,
	9, -3, -15, 9, 5, -22, 21, -24, 8, -26,
	9, 20, 5, 6, 30, 28, 5, 6, 5, 31,
	32, 5, 32, 5, 23, 5, 28, 5, 9, 8,
	-3, 8, 9, -3, 32, -3, 9, -2, 9, 9,
	32, 21, 7, 29, 7, 9, 32, 9, 33, 29,
	8, 28, 30, 9, -3, -17, 9, 9, 26, 9,
	13, 8, -14, -1, -5, 9, 28, 10, -18, 18,
	19, 7, 33, 33, -2, 7, -5, 9, -5, 31,
	9, -2, 9, 14, 29, 9, 33, 33, 7, 33,
	9, 25, 29, 9, 33, 7, -9, -1, -8, 9,
	33, -21, 34, 9, -5, -8, 9, 30, 31, 21,
	22, 9, 8,
}

var yyDef = [...]int8{
	0, -2, 1, 2, 3, 4, 5, 6, 7, 8,
	9, 10, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 37, 0, 0, 15, 0, 0, 0, 0, 0,
	0, 0, 11, 0, 0, 0, 12, 0, 13, 0,
	0, 14, 0, 16, 0, 17, 0, 18, 0, 0,
	0, 23, 0, 0, 0, 36, 0, 0, 19, 0,
	0, 46, 0, 0, 0, 0, 42, 20, 0, 0,
	0, 0, 0, 32, 26, 0, 0, 0, 0, 0,
	0, 24, 33, 26, 35, 21, 0, 25, 26, 38,
	39, 0, 0, 0, 0, 0, 34, 0, 40, 0,
	0, 0, -2, 0, 22, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 44, 0, 26, 0, 29, -2,
	0, 0, 0, 47, 27, 28, 30, 0, 41, 45,
	0, 31, 43,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 32,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 33,
	28, 29, 3, 3, 34, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 31,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 30,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:259
		{
			yylex.(*lexer).res = yyDollar[1].CombatLine
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:264
		{
			yyVAL.CombatLine.Damage = &yyDollar[1].Damage
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:267
		{
			yyVAL.CombatLine.Heal = &yyDollar[1].Heal
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:270
		{
			yyVAL.CombatLine.Kill = &yyDollar[1].Kill
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:273
		{
			yyVAL.CombatLine.Participant = &yyDollar[1].Participant
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:276
		{
			yyVAL.CombatLine.Start = &yyDollar[1].Start
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:279
		{
			yyVAL.CombatLine.Finished = &yyDollar[1].Finished
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:282
		{
			yyVAL.CombatLine.Reward = &yyDollar[1].Reward
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:285
		{
			yyVAL.CombatLine.ConnectToGameSession = &yyDollar[1].ConnectToGameSession
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:287
		{
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gramma.y:291
		{
			yyVAL.Damage = yyDollar[4].Damage
			yyVAL.Damage.Time = yyDollar[1].Time
		}
	case 12:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gramma.y:296
		{
			yyVAL.Heal = yyDollar[4].Heal
			yyVAL.Heal.Time = yyDollar[1].Time
		}
	case 13:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gramma.y:301
		{
			yyVAL.Kill = yyDollar[4].Kill
			yyVAL.Kill.Time = yyDollar[1].Time
		}
	case 14:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gramma.y:306
		{
			yyVAL.Participant = yyDollar[4].Participant
			yyVAL.Participant.Time = yyDollar[1].Time
		}
	case 15:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gramma.y:311
		{
			yyVAL.ConnectToGameSession = yyDollar[3].ConnectToGameSession
			yyVAL.ConnectToGameSession.Time = yyDollar[1].Time
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gramma.y:316
		{
			yyVAL.Start = yyDollar[4].Start
			yyVAL.Start.Time = yyDollar[1].Time
		}
	case 17:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gramma.y:321
		{
			yyVAL.Finished = yyDollar[4].Finished
			yyVAL.Finished.Time = yyDollar[1].Time
		}
	case 18:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gramma.y:326
		{

		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:334
		{
			yyVAL.Strings = append(yyVAL.Strings, yyDollar[1].String)
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gramma.y:334
		{
			yyVAL.Strings = append(yyDollar[1].Strings, yyDollar[2].String)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:335
		{
			yyVAL.String = yyDollar[1].String
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gramma.y:335
		{
			yyVAL.String = yyDollar[2].String
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gramma.y:337
		{
			yyVAL.Object = Object{
				Name:     yyDollar[1].String,
				ObjectID: yyDollar[3].Int,
			}
		}
	case 24:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gramma.y:343
		{
			yyVAL.Object = Object{
				PlayerObject: PlayerObject{
					ObjectName:  yyDollar[1].String,
					ObjectOwner: yyDollar[3].String,
				},
				ObjectID: yyDollar[6].Int,
			}
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:353
		{
			yyVAL.Bool = true
		}
	case 26:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gramma.y:353
		{
		}
	case 27:
		yyDollar = yyS[yypt-12 : yypt+1]
//line gramma.y:358
		{
			yyVAL.Damage = Damage{
				Initiator:       yyDollar[1].Object,
				Recipient:       yyDollar[3].Object,
				DamageFull:      yyDollar[4].Float,
				DamageHull:      yyDollar[7].Float,
				DamageShield:    yyDollar[9].Float,
				Source:          yyDollar[11].DamageSucks.Source,
				DamageModifiers: yyDollar[11].DamageSucks.Modifiers,
				FriendlyFire:    yyDollar[12].Bool,
			}
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gramma.y:371
		{
			yyVAL.DamageSucks.Source = yyDollar[1].String
			yyVAL.DamageSucks.Modifiers = yyDollar[2].DamageModifiersMap
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:374
		{
			yyVAL.DamageSucks.Modifiers = yyDollar[1].DamageModifiersMap
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:378
		{
			yyVAL.DamageModifiersMap = DamageModifiersMap{
				DamageModifier(yyDollar[1].String): {},
			}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gramma.y:382
		{
			yyVAL.DamageModifiersMap[DamageModifier(yyDollar[3].String)] = struct{}{}
		}
	case 32:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gramma.y:389
		{
			yyVAL.Heal = Heal{
				Initiator: yyDollar[1].Object,
				Recipient: yyDollar[3].Object,
				Heal:      yyDollar[4].Float,
				Source:    yyDollar[5].String,
			}
		}
	case 33:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gramma.y:403
		{
			if yyDollar[4].String != "killer" {
				yylex.Error("not a killer")
			}
			yyVAL.Kill = Kill{
				Killed:       yyDollar[1].Object,
				Killer:       yyDollar[5].Object,
				Source:       yyDollar[6].KillSucks.Source,
				FriendlyFire: yyDollar[6].KillSucks.FriendlyFire,
			}
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gramma.y:415
		{
			yyVAL.KillSucks.Source = yyDollar[1].String
			yyVAL.KillSucks.FriendlyFire = yyDollar[2].Bool
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:418
		{
			yyVAL.KillSucks.FriendlyFire = yyDollar[1].Bool
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gramma.y:420
		{
			yyVAL.Object = Object{
				Name: yyDollar[1].String,
				PlayerObject: PlayerObject{
					ObjectName: yyDollar[3].Object.Name,
				},
				ObjectID: yyDollar[3].Object.ObjectID,
			}
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:428
		{
			yyVAL.Object = yyDollar[1].Object
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:433
		{
			yyVAL.BuffDebuff.IsBuff = true
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:433
		{
			yyVAL.BuffDebuff.IsDebuff = true
		}
	case 40:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gramma.y:440
		{
			yyVAL.Participant = Participant{
				Name:           yyDollar[1].String,
				Ship:           yyDollar[3].String,
				Damage:         yyDollar[5].Participant.Damage,
				MostDamageWith: yyDollar[5].Participant.MostDamageWith,
				BuffDebuff:     yyDollar[6].BuffDebuff,
				FriendlyFire:   yyDollar[7].Bool,
			}
		}
	case 41:
		yyDollar = yyS[yypt-8 : yypt+1]
//line gramma.y:451
		{
			yyVAL.Participant.Damage = yyDollar[2].Float
			yyVAL.Participant.MostDamageWith = yyDollar[6].String
		}
	case 42:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gramma.y:454
		{
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gramma.y:458
		{
			yyVAL.Int = yyDollar[3].Int
		}
	case 44:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gramma.y:458
		{
		}
	case 45:
		yyDollar = yyS[yypt-12 : yypt+1]
//line gramma.y:462
		{
			yyVAL.Start = Start{
				What:              strings.Join(yyDollar[3].Strings, " "),
				GameMode:          yyDollar[5].String,
				MapName:           yyDollar[9].String,
				LocalClientTeamID: yyDollar[11].Int,
			}
		}
	case 46:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gramma.y:474
		{
			yyVAL.ConnectToGameSession.SessionID = yyDollar[3].Int
		}
	case 47:
		yyDollar = yyS[yypt-11 : yypt+1]
//line gramma.y:482
		{
			yyVAL.Finished = Finished{
				WinnerTeamID: yyDollar[1].Int,
				WinReason:    yyDollar[3].String,
				FinishReason: strings.Join(yyDollar[7].Strings, " "),
				GameTime:     yyDollar[10].Float,
			}
		}
	case 48:
		yyDollar = yyS[yypt-7 : yypt+1]
//line gramma.y:494
		{

		}
	}
	goto yystack /* stack new state and value */
}
