// Code generated by goyacc -o parser.go gramma.y. DO NOT EDIT.

//line gramma.y:2
package main

import __yyfmt__ "fmt"

//line gramma.y:2

import (
	"strings"
	"time"
)

type LogLine[T any] struct {
	LogTime time.Time
	Line    T
}

type CombatLine struct {
	*Damage
	*Heal
	*ConnectToGameSession
	*Start
	*Kill
}

type ConnectToGameSession struct {
	SessionID int
}

type Start struct {
	What              string
	GameMode          string
	MapName           string
	LocalClientTeamID int
}

type Damage struct {
	Initiator Object
	Recipient Object
	Source    string

	DamageFull      float32
	DamageHull      float32
	DamageShield    float32
	DamageModifiers DamageModifiersMap

	FriendlyFire bool
}

type Heal struct {
	Initiator Object
	Recipient Object
	Source    string

	Heal float32
}

type Kill struct {
	Killed       Object
	Killer       Object
	Source       string
	FriendlyFire bool
}

type PlayerObject struct {
	ObjectName  string
	ObjectOwner string
}

type Object struct {
	Name string
	PlayerObject
	ObjectID int
}

type DamageModifier string
type DamageModifiersMap map[DamageModifier]struct{}

// TODO string to enum 1 << iota
const (
	DamageTypeEMP         DamageModifier = "EMP"
	DamageTypeKinetic     DamageModifier = "KINETIC"
	DamageTypeThermal     DamageModifier = "THERMAL"
	DamageTypeTrueDamage  DamageModifier = "TRUE_DAMAGE"
	DamageUnintention     DamageModifier = "UNINTENTION"
	DamageCrit            DamageModifier = "CRIT"
	DamageExplosion       DamageModifier = "EXPLOSION"
	DamageCollision       DamageModifier = "COLLISION"
	DamageWeaponPrimary   DamageModifier = "PRIMARY_WEAPON"
	DamageWeaponSecondary DamageModifier = "SECONDARY_WEAPON"
	DamageIgnoreScale     DamageModifier = "IGNORE_DAMAGE_SCALE"
	DamageIgnoreShield    DamageModifier = "IGNORE_SHIELD"
	DamageModule          DamageModifier = "MODULE"
)

type damageSucks struct {
	Source    string
	Modifiers DamageModifiersMap
}

type killSucks struct {
	Source       string
	FriendlyFire bool
}

//line gramma.y:104
type yySymType struct {
	yys     int
	String  string
	Strings []string
	Int     int
	Float   float32
	Bool    bool

	Time time.Time

	CombatLine  *LogLine[*CombatLine]
	CombatLines []*LogLine[*CombatLine]
	Combat      *CombatLine

	Damage          *Damage
	DamageSucks     damageSucks
	DamageModifiers DamageModifiersMap
	Object          Object

	Heal      *Heal
	Kill      *Kill
	KillSucks killSucks
}

const COMBAT = 57346
const GAME = 57347
const EOL = 57348
const ARROW = 57349
const DAMAGE = 57350
const DAMAGE_HULL_START = 57351
const DAMAGE_SHIELD_START = 57352
const HEAL = 57353
const KILL = 57354
const CONNECT_TO_GAME_SESSION_PREFIX = 57355
const EQ_DELIM = 57356
const LOCAL_CLIENT_TEAM = 57357
const START = 57358
const FLOAT = 57359
const INT = 57360
const STRING = 57361
const FRIENDLY_FIRE = 57362
const TIME = 57363

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"COMBAT",
	"GAME",
	"EOL",
	"ARROW",
	"DAMAGE",
	"DAMAGE_HULL_START",
	"DAMAGE_SHIELD_START",
	"HEAL",
	"KILL",
	"CONNECT_TO_GAME_SESSION_PREFIX",
	"EQ_DELIM",
	"LOCAL_CLIENT_TEAM",
	"START",
	"FLOAT",
	"INT",
	"STRING",
	"FRIENDLY_FIRE",
	"TIME",
	"'\\''",
	"','",
	"'('",
	"')'",
	"';'",
	"'\\t'",
	"'|'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line gramma.y:303

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 77,
	19, 26,
	-2, 28,
}

const yyPrivate = 57344

const yyLast = 90

var yyAct = [...]int8{
	76, 56, 57, 15, 27, 27, 83, 30, 26, 26,
	49, 38, 58, 60, 18, 22, 29, 59, 77, 71,
	67, 44, 48, 59, 73, 42, 70, 65, 41, 34,
	52, 4, 37, 5, 39, 60, 85, 82, 68, 64,
	61, 16, 50, 47, 69, 46, 5, 36, 33, 21,
	51, 84, 54, 35, 31, 62, 45, 43, 23, 63,
	9, 24, 79, 10, 11, 78, 12, 40, 66, 53,
	28, 25, 13, 75, 7, 3, 81, 80, 6, 1,
	19, 17, 32, 72, 55, 74, 20, 14, 8, 2,
}

var yyPact = [...]int16{
	25, -1000, 12, -1000, -1000, 70, -1000, 52, 66, 22,
	22, 30, 45, -1000, -1000, 64, -19, -1000, 63, -1000,
	-10, -20, -1000, 36, 29, 22, 35, 28, 22, -16,
	22, 53, 6, -1000, 40, -1000, -4, 39, 26, -1000,
	-1000, 24, -1000, -2, -18, 23, 22, 8, 60, 34,
	-1000, -7, 21, 38, -1000, -1000, 15, -1000, -1000, 20,
	-1000, 5, 58, -1000, -5, 19, 27, -1000, 4, -6,
	1, -1, 51, 47, 15, 18, -22, -1000, -1000, 33,
	-1000, -22, -1000, 17, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 89, 75, 88, 87, 3, 86, 2, 0, 1,
	85, 84, 83, 82, 81, 80, 79,
}

var yyR1 = [...]int8{
	0, 16, 1, 1, 1, 2, 3, 3, 3, 3,
	3, 13, 13, 12, 12, 4, 14, 15, 11, 11,
	6, 6, 5, 5, 10, 10, 9, 9, 8, 8,
	7, 7,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 1, 4, 2, 2, 2, 4,
	12, 1, 2, 3, 0, 12, 5, 6, 2, 1,
	3, 1, 3, 6, 2, 1, 1, 3, 1, 3,
	1, 0,
}

var yyChk = [...]int16{
	-1000, -16, -1, -2, 6, 21, -2, 4, -3, 8,
	11, 12, 14, 6, -4, -5, 19, -14, -5, -15,
	-6, 19, -5, 13, 16, 7, 28, 24, 7, 26,
	27, 18, -13, 19, -5, 18, 19, -5, 27, -5,
	14, 22, 19, 17, 25, 17, 19, 19, 24, 28,
	19, -5, 22, 9, 18, -11, -9, -7, 19, 24,
	20, 19, 17, -7, 19, 22, 10, 25, 19, 17,
	22, 25, -12, 23, -10, -9, -8, 19, 14, 15,
	-7, -8, 19, 28, 18, 19,
}

var yyDef = [...]int8{
	0, -2, 1, 3, 4, 0, 2, 0, 0, 0,
	0, 0, 0, 5, 6, 0, 0, 7, 0, 8,
	0, 0, 21, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 11, 0, 22, 0, 0, 0, 20,
	9, 0, 12, 0, 0, 0, 0, 0, 0, 0,
	16, 31, 0, 0, 23, 17, 31, 19, 26, 0,
	30, 0, 0, 18, 0, 0, 0, 27, 0, 0,
	14, 0, 0, 0, 31, 0, 25, -2, 10, 0,
	15, 24, 28, 0, 13, 29,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 27,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 22,
	24, 25, 3, 3, 23, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 26,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 28,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:164
		{
			yylex.(*lexer).res = yyDollar[1].CombatLines
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gramma.y:168
		{
			yyVAL.CombatLines = append(yyDollar[1].CombatLines, yyDollar[2].CombatLine)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:168
		{
			yyVAL.CombatLines = append(yyVAL.CombatLines, yyDollar[1].CombatLine)
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:168
		{
		}
	case 5:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gramma.y:170
		{
			// println($1.String())
			yyVAL.CombatLine = &LogLine[*CombatLine]{
				LogTime: yyDollar[1].Time,
				Line:    yyDollar[3].Combat,
			}
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gramma.y:181
		{
			yyVAL.Combat = &CombatLine{
				Damage: yyDollar[2].Damage,
			}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gramma.y:185
		{
			yyVAL.Combat = &CombatLine{
				Heal: yyDollar[2].Heal,
			}
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gramma.y:189
		{
			yyVAL.Combat = &CombatLine{
				Kill: yyDollar[2].Kill,
			}
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gramma.y:193
		{
			yyVAL.Combat = &CombatLine{
				ConnectToGameSession: &ConnectToGameSession{SessionID: yyDollar[3].Int},
			}
		}
	case 10:
		yyDollar = yyS[yypt-12 : yypt+1]
//line gramma.y:197
		{
			yyVAL.Combat = &CombatLine{
				Start: &Start{
					What:              strings.Join(yyDollar[3].Strings, " "),
					GameMode:          yyDollar[5].String,
					MapName:           yyDollar[9].String,
					LocalClientTeamID: yyDollar[11].Int,
				},
			}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:208
		{
			yyVAL.Strings = append(yyVAL.Strings, yyDollar[1].String)
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gramma.y:208
		{
			yyVAL.Strings = append(yyDollar[1].Strings, yyDollar[2].String)
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gramma.y:210
		{
			yyVAL.Int = yyDollar[3].Int
		}
	case 14:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gramma.y:210
		{
		}
	case 15:
		yyDollar = yyS[yypt-12 : yypt+1]
//line gramma.y:213
		{
			yyVAL.Damage = &Damage{
				Initiator:       yyDollar[1].Object,
				Recipient:       yyDollar[3].Object,
				DamageFull:      yyDollar[4].Float,
				DamageHull:      yyDollar[7].Float,
				DamageShield:    yyDollar[9].Float,
				Source:          yyDollar[11].DamageSucks.Source,
				DamageModifiers: yyDollar[11].DamageSucks.Modifiers,
				FriendlyFire:    yyDollar[12].Bool,
			}
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gramma.y:227
		{
			yyVAL.Heal = &Heal{
				Initiator: yyDollar[1].Object,
				Recipient: yyDollar[3].Object,
				Heal:      yyDollar[4].Float,
				Source:    yyDollar[5].String,
			}
		}
	case 17:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gramma.y:239
		{
			if yyDollar[4].String != "killer" {
				yylex.Error("not a killer")
			}
			yyVAL.Kill = &Kill{
				Killed:       yyDollar[1].Object,
				Killer:       yyDollar[5].Object,
				Source:       yyDollar[6].KillSucks.Source,
				FriendlyFire: yyDollar[6].KillSucks.FriendlyFire,
			}
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gramma.y:251
		{
			yyVAL.KillSucks.Source = yyDollar[1].String
			yyVAL.KillSucks.FriendlyFire = yyDollar[2].Bool
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:254
		{
			yyVAL.KillSucks.FriendlyFire = yyDollar[1].Bool
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gramma.y:256
		{
			yyVAL.Object = Object{
				Name: yyDollar[1].String,
				PlayerObject: PlayerObject{
					ObjectName: yyDollar[3].Object.Name,
				},
				ObjectID: yyDollar[3].Object.ObjectID,
			}
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:264
		{
			yyVAL.Object = yyDollar[1].Object
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gramma.y:268
		{
			yyVAL.Object = Object{
				Name:     yyDollar[1].String,
				ObjectID: yyDollar[3].Int,
			}
		}
	case 23:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gramma.y:274
		{
			yyVAL.Object = Object{
				PlayerObject: PlayerObject{
					ObjectName:  yyDollar[1].String,
					ObjectOwner: yyDollar[3].String,
				},
				ObjectID: yyDollar[6].Int,
			}
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gramma.y:284
		{
			yyVAL.DamageSucks.Source = yyDollar[1].String
			yyVAL.DamageSucks.Modifiers = yyDollar[2].DamageModifiers
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:287
		{
			yyVAL.DamageSucks.Modifiers = yyDollar[1].DamageModifiers
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:291
		{
			yyVAL.String = yyDollar[1].String
		}
	case 27:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gramma.y:291
		{
			yyVAL.String = yyDollar[2].String
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:293
		{
			yyVAL.DamageModifiers = DamageModifiersMap{
				DamageModifier(yyDollar[1].String): {},
			}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gramma.y:297
		{
			yyVAL.DamageModifiers[DamageModifier(yyDollar[3].String)] = struct{}{}
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gramma.y:301
		{
			yyVAL.Bool = true
		}
	case 31:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gramma.y:301
		{
		}
	}
	goto yystack /* stack new state and value */
}
