// Code generated by "stringer -type=CombatLogLineType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CombatLogLineTypeConnectToGameSession-0]
	_ = x[CombatLogLineTypeStartGameplay-1]
	_ = x[CombatLogLineTypeDamage-2]
	_ = x[CombatLogLineTypeHeal-3]
	_ = x[CombatLogLineTypeKill-4]
	_ = x[CombatLogLineTypeGameplayFinished-5]
}

const _CombatLogLineType_name = "CombatLogLineTypeConnectToGameSessionCombatLogLineTypeStartGameplayCombatLogLineTypeDamageCombatLogLineTypeHealCombatLogLineTypeKillCombatLogLineTypeGameplayFinished"

var _CombatLogLineType_index = [...]uint8{0, 37, 67, 90, 111, 132, 165}

func (i CombatLogLineType) String() string {
	if i < 0 || i >= CombatLogLineType(len(_CombatLogLineType_index)-1) {
		return "CombatLogLineType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CombatLogLineType_name[_CombatLogLineType_index[i]:_CombatLogLineType_index[i+1]]
}
