// Code generated by "stringer -type=DamageType"; DO NOT EDIT.

package service

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DamageTypeTotal-0]
	_ = x[DamageTypeHull-1]
	_ = x[DamageTypeShield-2]
}

const _DamageType_name = "DamageTypeTotalDamageTypeHullDamageTypeShield"

var _DamageType_index = [...]uint8{0, 15, 29, 45}

func (i DamageType) String() string {
	if i < 0 || i >= DamageType(len(_DamageType_index)-1) {
		return "DamageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DamageType_name[_DamageType_index[i]:_DamageType_index[i+1]]
}
